name: Go Build

on:
  push:
    branches: [ main ] # Triggers the workflow on push events to the main branch
  pull_request:
    branches: [ main ] # Triggers the workflow on pull request events targeting the main branch

jobs:
  build-go-apps:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Specify your Go version, e.g., 1.21, 1.20, etc.

    - name: Get Go module dependencies
      run: go mod download

    - name: Build apiserver
      run: go build -v -o bin/apiserver ./cmd/apiserver

    - name: Build chatserver
      run: go build -v -o bin/chatserver ./cmd/chatserver

    - name: Upload apiserver artifact
      uses: actions/upload-artifact@v4
      with:
        name: apiserver
        path: bin/apiserver

    - name: Upload chatserver artifact
      uses: actions/upload-artifact@v4
      with:
        name: chatserver
        path: bin/chatserver
